Check for SUPABASE in .env.preview.local
Add step to check for SUPABASE in env file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,6 +42,8 @@ jobs:
         run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel
         run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Check env file
+        run: cat .vercel/.env.preview.local | grep SUPABASE || echo "NOT FOUND"
 
   deploy-production:
     needs: build-and-test
